name: native_pdf_renderer
description: Flutter plugin to render PDF pages as images on Web, MacOS, Android and iOS.
version: 2.4.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_renderer

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  device_info: 2.0.0-nullsafety.1
  js: 0.6.3-nullsafety.3
  synchronized: 3.0.0-nullsafety.1
  uuid: 3.0.0-nullsafety.0
  extension:
    git:
      url: https://github.com/Three-Horsemen-of-Software-Engineering/packages.dart.git
      ref: extension/migration/null-safety
      path: packages/extension

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        pluginClass: NativePdfRendererPlugin
        package: io.scer.pdf.renderer
      ios:
        pluginClass: NativePdfRendererPlugin
      macos:
        pluginClass: NativePdfRendererPlugin
      web:
        pluginClass: NativePdfRendererPlugin
        fileName: src/web/native_pdf_renderer_plugin.dart
